Revert debug-related changes, fix formatting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,8 +33,8 @@ jobs:
             ruby: jruby-9.4.3.0
           - os: "macos-latest"
             ruby: jruby-9.4.3.0
-#          - os: "windows-latest"
-#            ruby: jruby-9.4.3.0
+          - os: "windows-latest"
+            ruby: jruby-9.4.3.0
     steps:
       - uses: actions/checkout@v3
 
@@ -44,7 +44,7 @@ jobs:
           distribution: 'temurin'
           java-version: '17'
 
-      - uses: uvlad7/oxidize-rb-actions/setup-ruby-and-rust@main
+      - uses: actions/setup-java@v4
         with:
           ruby-version: ${{ matrix.ruby }}
           bundler-cache: true
@@ -57,16 +57,15 @@ jobs:
       - name: Lint rust
         run: cargo clippy && cargo fmt --check
 
-      # Temporary disable until new rb-sys gem is released
-#      - name: Test source gem
-#        shell: bash
-#        run: |
-#          bundle exec rake build
-#          gem install --verbose pkg/*.gem
-#
-#          if ruby -roxi/test -e "puts Oxi::Test.hello('world!')" | grep "Hello, world!"; then
-#            echo "Success"
-#          else
-#            echo "Failure"
-#            exit 1
-#          fi
+      - name: Test source gem
+        shell: bash
+        run: |
+          bundle exec rake build
+          gem install --verbose pkg/*.gem
+
+          if ruby -roxi/test -e "puts Oxi::Test.hello('world!')" | grep "Hello, world!"; then
+            echo "Success"
+          else
+            echo "Failure"
+            exit 1
+          fi
