Configure source gem (#5)
* Configure source gem

* Better matrices

* Bunch of comments

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,12 +9,27 @@ on:
   pull_request:
 
 jobs:
+  ci-data:
+    runs-on: ubuntu-latest
+    outputs:
+      result: ${{ steps.fetch.outputs.result }}
+    steps:
+      - id: fetch
+        uses: oxidize-rb/actions/fetch-ci-data@main
+        with:
+          stable-ruby-versions: |
+            exclude: []
   ci:
     runs-on: ${{ matrix.os }}
+    needs: ci-data
     strategy:
       matrix:
         os: ["ubuntu-latest", "macos-latest", "windows-latest"]
-        ruby: ["2.6", "2.7", "3.0", "3.1", "head"]
+        ruby: ${{ fromJSON(needs.ci-data.outputs.result).stable-ruby-versions }}
+        # Unstable until Ruby 3.2
+        # include:
+        #   - os: windows-latest
+        #     ruby: mswin
     steps:
       - uses: actions/checkout@v3
 
@@ -30,3 +45,16 @@ jobs:
 
       - name: Lint rust
         run: cargo clippy && cargo fmt --check
+
+      - name: Test source gem
+        shell: bash
+        run: |
+          bundle exec rake build
+          gem install --verbose pkg/*.gem
+
+          if ruby -roxi/test -e "puts Oxi::Test.hello('world!')" | grep "Hello, world!"; then
+            echo "Success"
+          else
+            echo "Failure"
+            exit 1
+          fi
